
export const SELECT_TAB = 'SELECT_TAB';
export const GET_ALL_VANTAGE_POINTS = 'GET_ALL_VANTAGE_POINTS';
export const SET_CURRENT_VANTAGE_POINT = 'SET_CURRENT_VANTAGE_POINT';
export const SHOW_VANTAGE_POINT_MAP = 'SHOW_VANTAGE_POINT_MAP';
export const HIDE_VANTAGE_POINT_MAP = 'HIDE_VANTAGE_POINT_MAP';
